# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

# Pointing to the layers you downloaded in ~/stuff
LAYERSDIR = "${HOME}/stuff"

BBLAYERS ?= " \
  ${LAYERSDIR}/poky/meta \
  ${LAYERSDIR}/poky/meta-poky \
  ${LAYERSDIR}/poky/meta-yocto-bsp \
  ${LAYERSDIR}/meta-openembedded/meta-oe \
  ${LAYERSDIR}/meta-openembedded/meta-python \
  ${LAYERSDIR}/meta-openembedded/meta-multimedia \
  ${LAYERSDIR}/meta-openembedded/meta-networking \
  ${LAYERSDIR}/meta-raspberrypi \
  "